# Generated by Django 4.1.7 on 2023-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('person_email', models.EmailField(max_length=250)),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('counter_login', models.IntegerField(default=0, max_length=50)),
                ('data_reg', models.DateField(auto_now_add=True)),
                ('lust_login', models.DateField(auto_now=True)),
            ],
        ),
    ]
