# Generated by Django 4.1.7 on 2023-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mykola', '0003_alter_users_options_users_person_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
